#!/usr/bin/env python3
"""references/tables/pulse_table_audited.xlsx  ->  db/seed.sql

The workbook is the audited source of truth.  This turns its Event_sources /
Finite_fault_segments / Station_coords / Pulse_records sheets into INSERT
statements matching db/schema.sql, so the same file seeds a local SQLite DB
and a Cloudflare D1 database:

    python scripts/load_workbook.py                 # writes db/seed.sql
    python scripts/load_workbook.py --sqlite db/site.dev.db   # + build a local DB

    # then, against D1:
    wrangler d1 migrations apply pulse_db
    wrangler d1 execute pulse_db --file=db/seed.sql --remote
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[1]
XLSX = ROOT / "references" / "tables" / "pulse_table_audited.xlsx"
SEED = ROOT / "db" / "seed.sql"
JWB = "https://www.jackwbaker.com/pulse_classification_v2"

# source_sheet  ->  catalog id shown on the site  (others are loaded but hidden).
# The YEN catalog is Yen(2022) + the fling-corrected 2023 additions (Türkiye,
# Düzce 2022) -- together the curated Yen(2025) list, 118 records / 9 events.
# Yen_uncorr_fling(2023) is the uncorrected duplicate set and stays hidden.
CATALOG_MAP = {
    "Baker(2014)": "shahi_baker_2014",
    "Taiwan database(NCREE)": "taiwan_ncree",
    "Yen(2022)": "yen_2022",
    "Yen_corr_fling(2023)": "yen_2022",
}
# Catalog display metadata (the workbook has no catalog-label sheet).  label =
# compact form in the "Data source" selector; citation = text under it.
CATALOGS = [
    dict(id="shahi_baker_2014", label="S&B", short="S&B 2014",
         citation="Ground motions in the NGA-West2 database that were identified "
                  "as pulse-like using the Shahi and Baker (2014) model.",
         url=f"{JWB}/Pulse-like-records.html", pulse_only=0, sort_order=1),
    dict(id="taiwan_ncree", label="NCREE", short="NCREE",
         citation="Database of Near-Fault Strong Motions with Pulse-like "
                  "Velocity from NCREE, using the Shahi and Baker (2014) model.",
         url="https://nfpv.ncree.org.tw/", pulse_only=0, sort_order=2),
    dict(id="yen_2022", label="YEN", short="YEN",
         citation="Identified pulses from Yen et al.(2022), "
                  "Türker et al. (2024) and Yen et al. (2025), using the "
                  "Shahi and Baker (2014) model.",
         url="", pulse_only=1, sort_order=3),
]


def sv(x):
    """Python value -> SQL literal."""
    if x is None or (isinstance(x, str) and x.strip() in ("", "NaN", "None")):
        return "NULL"
    if isinstance(x, bool):
        return "1" if x else "0"
    if isinstance(x, (int, float)):
        return repr(x)
    return "'" + str(x).replace("'", "''") + "'"


def _num(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def _sheet(wb, name):
    ws = wb[name]
    it = ws.iter_rows(values_only=True)
    head = [str(h).strip() if h is not None else "" for h in next(it)]
    return head, [dict(zip(head, r)) for r in it]


def _year(event_key):
    return int(event_key[:4]) if event_key and event_key[:4].isdigit() else None


# tables in child -> parent order, for a safe DELETE sweep before re-seeding
WIPE_ORDER = ["pulse_records", "fault_segments", "stations", "events", "catalogs"]


def _insert(table, cols, rows):
    if not rows:
        return ""
    out = []
    for i in range(0, len(rows), 100):
        chunk = rows[i:i + 100]
        out.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES")
        out.append(",\n".join("(" + ", ".join(sv(r.get(c)) for c in cols) + ")"
                              for r in chunk) + ";")
    return "\n".join(out) + "\n\n"


def build():
    wb = openpyxl.load_workbook(XLSX, read_only=True, data_only=True)

    # -- catalogs -------------------------------------------------------------
    cat_cols = ["id", "label", "short", "citation", "url", "pulse_only",
                "sort_order"]
    # D1 ignores `PRAGMA foreign_keys`; `defer_foreign_keys` postpones the FK
    # check to COMMIT so the wipe + reload order inside one batch is allowed.
    sql = ["-- generated by scripts/load_workbook.py  --  do not edit\n",
           "PRAGMA defer_foreign_keys = TRUE;\n",
           "".join(f"DELETE FROM {t};\n" for t in WIPE_ORDER) + "\n",
           _insert("catalogs", cat_cols, CATALOGS)]

    # -- events (Event_sources) --------------------------------------------- --
    _, es = _sheet(wb, "Event_sources")
    events = []
    for r in es:
        ek = r["event_key"]
        if not ek:
            continue
        names = r.get("event_names") or ek
        events.append(dict(
            event_key=ek, name=str(names).split("|")[0].strip(), names=names,
            year=_year(ek), origin_utc=_origin(r),
            mag=_num(r.get("catalog_magnitude")), mag_type=r.get("magnitude_type"),
            hypo_lat=_num(r.get("hypo_latitude_deg")),
            hypo_lon=_num(r.get("hypo_longitude_deg")),
            hypo_depth_km=_num(r.get("hypo_depth_km")),
            mechanism=r.get("mechanism"), plane_definition=r.get("plane_definition"),
            strike1=_num(r.get("strike1_deg")), dip1=_num(r.get("dip1_deg")),
            rake1=_num(r.get("rake1_deg")),
            strike2=_num(r.get("strike2_deg")), dip2=_num(r.get("dip2_deg")),
            rake2=_num(r.get("rake2_deg")),
            nga_strike=_num(r.get("nga_strike_deg")),
            nga_dip=_num(r.get("nga_dip_deg")), nga_rake=_num(r.get("nga_rake_deg")),
            nga_length_km=_num(r.get("nga_length_km")),
            nga_width_km=_num(r.get("nga_width_km")),
            nga_ztor_km=_num(r.get("nga_ztor_km")),
            usgs_event_id=r.get("usgs_event_id"), source_url=r.get("source_url"),
            ff_status=r.get("ff_status"), ff_url=r.get("ff_url"),
            ff_fsp_url=r.get("ff_fsp_url"),
            ff_model_mw=_num(r.get("ff_model_Mw")),
            ff_max_slip_m=_num(r.get("ff_max_slip_m")),
            ff_model_area_km2=_num(r.get("ff_model_area_km2")),
            ff_segment_count=_num(r.get("ff_segment_count")),
        ))
    ev_cols = ["event_key", "name", "names", "year", "origin_utc", "mag",
               "mag_type", "hypo_lat", "hypo_lon", "hypo_depth_km", "mechanism",
               "plane_definition", "strike1", "dip1", "rake1", "strike2", "dip2",
               "rake2", "nga_strike", "nga_dip", "nga_rake", "nga_length_km",
               "nga_width_km", "nga_ztor_km", "usgs_event_id", "source_url",
               "ff_status", "ff_url", "ff_fsp_url", "ff_model_mw", "ff_max_slip_m",
               "ff_model_area_km2", "ff_segment_count"]
    sql.append(_insert("events", ev_cols, events))

    # -- fault_segments (Finite_fault_segments) --------------------------------
    _, ffs = _sheet(wb, "Finite_fault_segments")
    seg_cols = ["event_key", "segment", "strike_deg", "dip_deg", "length_km",
                "width_km", "area_km2", "top_depth_km", "subfault_count",
                "max_slip_m", "rake_min_deg", "rake_max_deg", "fsp_url"]
    segs = [dict(
        event_key=r["event_key"], segment=int(r["segment"] or 1),
        strike_deg=_num(r.get("strike_deg")), dip_deg=_num(r.get("dip_deg")),
        length_km=_num(r.get("model_length_km")),
        width_km=_num(r.get("model_width_km")),
        area_km2=_num(r.get("model_area_km2")),
        top_depth_km=_num(r.get("top_depth_km")),
        subfault_count=_num(r.get("subfault_count")),
        max_slip_m=_num(r.get("max_slip_m")),
        rake_min_deg=_num(r.get("rake_min_deg")),
        rake_max_deg=_num(r.get("rake_max_deg")), fsp_url=r.get("fsp_url"),
    ) for r in ffs if r.get("event_key")]
    sql.append(_insert("fault_segments", seg_cols, segs))

    # -- stations (Station_coords) -------------------------------------------- --
    _, sc = _sheet(wb, "Station_coords")
    st_cols = ["station_key", "names", "lat", "lon", "coord_status", "coord_note"]
    seen, stations = set(), []
    for r in sc:
        k = r.get("station_key")
        if not k or k in seen:
            continue
        seen.add(k)
        stations.append(dict(
            station_key=k, names=r.get("station_names"),
            lat=_num(r.get("latitude_deg")), lon=_num(r.get("longitude_deg")),
            coord_status=r.get("coord_status"), coord_note=r.get("coord_note")))
    sql.append(_insert("stations", st_cols, stations))

    # -- pulse_records (Pulse_records) -------------------------------------- --
    _, pr = _sheet(wb, "Pulse_records")
    pr_cols = ["record_id", "source_sheet", "catalog_id", "event_key",
               "station_key", "station_label", "nga_rsn", "lat", "lon",
               "coord_status", "mw", "tp_s", "tf_s", "pgv_cm_s", "rrup_km",
               "rhyp_km", "vs30", "ori_north_deg", "ori_fp_deg", "is_pulse",
               "directivity", "fling", "quality_flag", "summary_url"]
    recs = []
    for r in pr:
        rid = r["record_id"]
        if not rid:
            continue
        ss = r["source_sheet"]
        cat = CATALOG_MAP.get(ss)
        rsn = str(r["NGA_RSN"]).strip() if r.get("NGA_RSN") not in (None, "") else None
        pgv = _num(r.get("PGV_cm_s"))
        if pgv is None:
            ew, ns = _num(r.get("PGV_EW_original")), _num(r.get("PGV_NS_original"))
            pgv = max([v for v in (ew, ns) if v is not None], default=None)
        fnp = r.get("fault_normal_pulse")
        is_pulse = 1 if (fnp == 1 or r.get("Ipulse_H") is True
                         or cat == "yen_2022") else 0
        recs.append(dict(
            record_id=rid, source_sheet=ss, catalog_id=cat,
            event_key=r.get("event_key"), station_key=r.get("station_key"),
            station_label=r.get("station_original"), nga_rsn=rsn,
            lat=_num(r.get("latitude_deg")), lon=_num(r.get("longitude_deg")),
            coord_status=r.get("coord_status"),
            mw=_num(r.get("Mw")),
            tp_s=_num(r.get("Tp_s")) if r.get("Tp_s") is not None
            else _num(r.get("Tp_H_s")),
            tf_s=_num(r.get("Tf_s")), pgv_cm_s=pgv,
            rrup_km=_num(r.get("Rrup_km")) if r.get("Rrup_km") is not None
            else _num(r.get("closest_distance_km")),
            rhyp_km=_num(r.get("Rhyp_km")),
            vs30=_num(r.get("vs30_original")),
            ori_north_deg=_num(r.get("orientation_north_deg")),
            ori_fp_deg=_num(r.get("orientation_fault_parallel_deg")),
            is_pulse=is_pulse,
            directivity=1 if r.get("directivity_effect") == 1 else
            (0 if r.get("directivity_effect") == 0 else None),
            fling=1 if r.get("fling") in (True, 1, "True") else
            (0 if r.get("fling") in (False, 0, "False") else None),
            quality_flag=(str(r["quality_flag"])
                          if r.get("quality_flag") not in (None, "") else None),
            summary_url=(f"{JWB}/{rsn}.html" if rsn and cat == "shahi_baker_2014"
                         else None),
        ))
    sql.append(_insert("pulse_records", pr_cols, recs))

    SEED.parent.mkdir(exist_ok=True)
    SEED.write_text("\n".join(sql))
    print(f"wrote {SEED.relative_to(ROOT)}  "
          f"({len(events)} events, {len(segs)} fault segments, "
          f"{len(stations)} stations, {len(recs)} pulse records; "
          f"{sum(1 for r in recs if r['catalog_id'])} in a site catalog)")
    return SEED.read_text()


def _origin(r):
    d, t = r.get("origin_date_utc"), r.get("origin_time_utc")
    if not d:
        return None
    return f"{d}T{t}" if t else str(d)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sqlite", metavar="PATH",
                    help="also build a local SQLite DB from schema.sql + seed.sql")
    args = ap.parse_args(argv)
    if not XLSX.exists():
        sys.exit(f"missing {XLSX}")
    seed_sql = build()

    if args.sqlite:
        p = Path(args.sqlite)
        p.unlink(missing_ok=True)
        con = sqlite3.connect(p)
        con.executescript((ROOT / "db" / "schema.sql").read_text())
        con.executescript(seed_sql)
        n = con.execute("SELECT count(*) FROM pulse_records "
                        "WHERE catalog_id IS NOT NULL").fetchone()[0]
        con.close()
        print(f"built {p}  ({n} catalog records)")


if __name__ == "__main__":
    main()
